### ISSUE TITLE
Could you please add the web site?

### ISSUE THREAD

**Issue by Sjord** [Mabi19/numbers#3]
I easily found this GitHub repo, but I had a hard time finding where it was deployed, on https://mabi.tmpinc.io/numbers/.

Could you add that URL to the GitHub repo?

One place to add it is in the repository _about_ section. Next to "about" in the right column there is a cog wheel:

![Screenshot 2023-11-02 at 08 53 25](https://github.com/Mabi19/numbers/assets/113030/17af5e1c-aacb-4bae-acb5-ff7f78628265)

And there you can edit the website of the project:

![Screenshot 2023-11-02 at 08 53 45](https://github.com/Mabi19/numbers/assets/113030/616f9908-18f2-4aef-a51c-8cbb4ad7a217)

**Comment by Mabi19** [comment]
I honestly didn't think anyone would come here from GitHub and not SoME3 itself. Will do this when I get back to my PC
