### ISSUE TITLE
Cool stuff! Was this inspired by a youtube video?

### ISSUE THREAD

**Issue by Echo-Heo** [Mabi19/numbers#4]
I noticed the structure is very similar to [this video](https://youtu.be/dQhj5RGtag0) so i was wondering if it was inspired by it. Not accusing you of plagiarism or anything, it's just a good way of explaining in and besides, even if you were I don't think explaining something in a similar way counts as plagiarism. Just wondering if it was an explanation (in which case I still do think it deserves a mention in it).

**Comment by Mabi19** [comment]
I recall watching that a long time ago. Might have gotten subconsciously inspired by it, though I've also loved this teaching style for quite a long time.

(I wrote the whole thing pretty much from memory, only consulting the standard for intricacies of rounding and NaN handling.)

I might put a link to it in there now, though.
